import arrow
from abc import ABCMeta


class CommitGenerator(metaclass=ABCMeta):
    """
    Base class for commit generator. It could be inherited by random
    generators, ascii to bitmap writers or plain pixed drawing.
    """

    """
    Returns a list of all commits generated by the specific class.
    """
    @abstractmethod
    def get_commits(self):
        pass

class Commit():
    """
    Commit model holding information about the commit
    """
    __slots__ = ('date')

    """
    Create simple commit with date.

    :param date: date to be commited. default now
    """
    def __init__(self, date=arrow.utcnow()):
        self.date = date
